### ISSUE TITLE
Adjustable weight for bold

### ISSUE THREAD

**Issue by max** [basscss/utility-typography#2]
Depending on the Typeface you use 700 (aka bold) may not be the appropriate weight. For example I find the 700 to be very heavy for Roboto. I'd like to use `.bold` for the 500 weight (Medium) instead. Would you accept a PR that makes this a variable with a default?

```
.bold {
  font-weight: var(--bold-weight);
}

:root {
  --bold-weight: bold;
}
```

**Comment by max** [comment]
This is usually not a big deal because if you declare the font-face yourself you can just use the medium weight font file for the bold declaration. If you're using something like Google Fonts, that doesn't work.

**Comment by max** [comment]
Or alternatively a `.medium`. Just thinking out loud now.

**Comment by jxnblk** [comment]
Maybe I'm misunderstanding you, but `--bold-font-weight` already exists, right?

See: https://github.com/basscss/utility-typography/blob/master/index.css#L3

**Comment by max** [comment]
![http://i.giphy.com/4pMX5rJ4PYAEM.gif](http://i.giphy.com/4pMX5rJ4PYAEM.gif)

**Comment by jxnblk** [comment]
Haha! May also be helpful to know about --heading-font-weight
